version: '3.7'

services:
  zharfa:
    container_name: zharfa
    build:
      context: .
      dockerfile: ./Dockerfile
    logging:
      options:
        max-file: "10"
        max-size: "10m"
    ports:
      - "8080:8080"
    env_file:
      - .env
    entrypoint: >
      bash -c "uvicorn main:application --host 0.0.0.0 --port 8080"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    logging:
      options:
        max-file: "10"
        max-size: "10m"
    volumes:
      - redis:/var/lib/redis/data

volumes:
  redis:
